<?php
/****
 * STATUS CODES
 * -------------
 *
 * OMBUWIRE_NOT_STARTED
 * OMBUWIRE_WIREFRAME
 * OMBUWIRE_DESIGN
 * OMBUWIRE_STATIC
 * OMBUWIRE_IN_PROGRESS
 * OMBUWIRE_IMPLEMENTED
 */

/*
function _ombuwire_sitemap() {

  $sitemap = array(
    'about' => array(
      '#title' => "About",
      '#status'    => OMBUWIRE_NOT_STARTED,
      'wireframe' => '/wf/8.jpg',
      'design'    => '/design/8.jpg',
      'static'    => '/static/8.html',
      '#children' => array(
        'about/test' => array(
          '#title'     => "About Testing!",
          '#status'    => OMBUWIRE_NOT_STARTED,
          'wireframe' => '/wf/8.jpg',
          'design'    => '/design/8.jpg',
          'static'    => '/static/8.html',
        ),
      ),
    ),
    'act' => array(
      '#title'     => "Act",
      '#status'    => OMBUWIRE_NOT_STARTED,
      'wireframe' => '/wf/8.jpg',
    ),
    'discover' => array(
      '#title'     => "Discover",
      '#status'    => OMBUWIRE_NOT_STARTED,
      'wireframe' => '/wf/8.jpg',
    ),
  );

  return $sitemap;
}
*/