<?php
/****
 * STATUS CODES
 * -------------
 *
 * NOT_STARTED
 * IN_PROGRESS
 * FINISHED
 */

/*
function _ombuwire_sitemap() {

  $sitemap = array(
    'about' => array(
      'title' => "About",
      'status'    => NOT_STARTED,
      'wireframe' => '/wf/8.jpg',
      'design'    => '/design/8.jpg',
      'static'    => '/static/8.html',
        '#children' => array(
          'about/test' => array(
            'title'     => "About Testing!",
            'status'    => NOT_STARTED,
            'wireframe' => '/wf/8.jpg',
            'design'    => '/design/8.jpg',
            'static'    => '/static/8.html',
          ),
        ),
      ),
    'act' => array(
      'title'     => "Act",
      'status'    => NOT_STARTED,
      'wireframe' => '/wf/8.jpg',
    ),
    'discover' => array(
      'title'     => "Discover",
      'status'    => NOT_STARTED,
      'wireframe' => '/wf/8.jpg',
    ),
  );

  return $sitemap;
}
*/